### ISSUE TITLE
question: Is the API public? 

### ISSUE THREAD

**Issue by LuchoTurtle** [palavrapasse/santos#32] opened 2023-02-13 00:05 UTC
Been tinkering with [palavrapasse.pt](www.palavrapasse.pt) and have been thoroughly impressed, awesome job lads! 🎉

I've played around with the API with [`locust`](https://locust.io/) and your throttling seems to be working! (and handling a great number of users making concurrent requests quite handsomely, if I may add 👍)

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/17494745/218344690-19937fab-ab28-4081-b02a-27da64e4165b.png">

Yeah, I'm aware that all of these requests are being 429'd but it still shows the merit of using Go!

However, when I visit the URL https://api.palavrapasse.pt/leaks, it seems that it's queriable without any restrictions. I don't know if this is an intended design choice or not. I don't know (even after perusing [`docs`](https://github.com/palavrapasse/docs)) if you are thinking super long-term or not, but this seems like it could tear down performance quite easily (especially when the number of records in your database grows), as it is returning an array of *all the leaks*. I can't replicate different users from different IPs targeting this URL but this could put quite a heavy load on the database. 

If the API is **not meant to be public**, I suggest checking the origin of the requests and blocking them if they're not coming from the deployed frontend domain/IP address. 

If the API is **meant to be public**, I guess this depends on how you want to rate limit your database. If this is the case, I guess this pretty much depends on your database scaling strategies (e.g. [database replication for SQLite](https://litereplica.io/)). But I think we're getting ahead of ourselves, as **many of the concerns** have already been covered by y'alls awesome design choices.

Keep up the great work!

**Comment by freitzzz** [comment] 2023-02-13 10:35
Hey @LuchoTurtle 

Awesome to hear positive and constructive feedback from you, and thank you for load testing our API, we will also try Locust on our end :D 

> However, when I visit the URL https://api.palavrapasse.pt/leaks, it seems that it's queriable without any restrictions. I don't know if this is an intended design choice or not.

It indeed is correct by design, we have an use case for that! https://github.com/palavrapasse/docs/blob/master/core/use-cases.md#003---list-all-leaks
You can also check the implementation in `query` service: https://github.com/palavrapasse/query/blob/master/internal/data/query.go#L54

>  I suggest checking the origin of the requests and blocking them if they're not coming from the deployed frontend domain/IP address.

That's true! We need to restrict the origin of the requests, we have the implementation already on `santos`, but I must admit that I forgotten to update our `.env` file to indicate that we can only receive requests from `https://palavrapasse.pt` 😿 Will a create an issue for this right away!

Also, how do you suggest to block requests that don't come from the IP address where our frontend is hosted? Since our website is static, all HTTP requests are performed with origin from the user browser, so we can't exactly block IPs. We do have a design spec to block IP's that perform more than 50 requests per an endpoint time period (see https://github.com/palavrapasse/docs/blob/master/core/throttle.md), but we haven't found an elegant way to do that yet!

> If the API is meant to be public,

Yes, we allow anyone to consume our API as long as they respect our endpoint throttling rules. We haven't thought about database replication, but I will also create an issue for that!

Thank you for your valuable feedback :)

**Comment by LuchoTurtle** [comment] 2023-02-13 10:51
You can close this if you want to 😎👉

**Comment by freitzzz** [comment] 2023-02-13 11:48
Actually `santos` is on Azure right now! I will close this issue, but if you want you can document what you have done in Azure in this issue: https://github.com/palavrapasse/santos/issues/33

**Closed** 2023-02-13 11:48 UTC
